apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: ai-lab-all-experimental 
  description: AI LAB Samples
spec:
  targets:
    - ./templates/sampleapp/template.yaml
    - ./templates/non-ai-lab-chatbot/template.yaml
    - ./templates/chatbot-java-quarkus/template.yaml