apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
{%- if values.supportApp %}
patchesStrategicMerge:
  - deployment-patch.yaml
{%- endif %}
resources:
  - ../../base
  {%- if not values.deployOnRemoteCluster %}
  - tekton-repositories/
  {%- endif %}
